services:
  photon:
    build:
      context: .
      dockerfile: Dockerfile
    image: enkodo/docker-photon:latest
    container_name: photon
    ports:
      - "2322:2322"
    volumes:
      - photon_data:/photon/photon_data
    restart: unless-stopped

volumes:
  photon_data:
