version: "2"
services:
  photon:
    build:
      context: .
      dockerfile: Dockerfile
    image: tonsnoei/photon-geocoder:latest
    volumes:
      - ${HOST_DATA_PATH:-./photon}:/photon
    ports:
      - ${HOST_PORT:-2322}:2322
